name: Windows

on:
  push:
    branches:
      - develop
      - main
      - release/*
  pull_request:
  workflow_dispatch: # Allows manual triggering

permissions:
  contents: read

jobs:
  clang:
    runs-on: windows-2022
    strategy:
      matrix:
        build_type: [Debug, Release]
        conan_profile: [msvc_vs.profile, llvm_clang_vs.profile]

    steps:
      - name: Lowercase variables
        id: lower
        run: |
          echo "build_type_lower=${{ matrix.build_type }}" | tr '[:upper:]' '[:lower:]' >> $GITHUB_OUTPUT
      - uses: actions/checkout@v5
      
      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install dependencies with uv
        shell: pwsh
        run: |
          uv sync
          $venvPath = Join-Path (Get-Location) ".venv\Scripts"
          echo $venvPath | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - run: conan --version
      - name: Run Conan install
        run: conan install raktr --output-folder=. -pr:a=profiles/${{ matrix.conan_profile }} -s:a build_type=${{ matrix.build_type }} -o:a='&:with_tests=True' --build=missing
      
      - name: Configure CMake
        run: cmake --preset conan-${{ steps.lower.outputs.build_type_lower }}
        working-directory: ./raktr/
      
      - name: Build
        run: cmake --build --preset conan-${{ steps.lower.outputs.build_type_lower }} --parallel 10
        working-directory: ./raktr/
      
      - name: Test
        run: cd build ; ctest -j 10 -C ${{ matrix.build_type }} --output-on-failure
