name: Windows

on:
  push:
    branches:
      - develop
      - main
      - release/*
  pull_request:
  workflow_dispatch: # Allows manual triggering

permissions:
  contents: read

jobs:
  clang:
    runs-on: windows-2022
    strategy:
      matrix:
        build_type: [Debug, Release]
        conan_profile: [msvc_vs.profile, llvm_clang_vs.profile]

    steps:
      - name: Lowercase variables
        id: lower
        run: |
          echo "build_type_lower=${{ matrix.build_type }}" | tr '[:upper:]' '[:lower:]' >> $GITHUB_OUTPUT
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: '3.13'
      - run: pip install uv
      - run: uv sync
      - run: conan --version
      - name: Run Conan install
        run: conan install raktr --output-folder=. -pr:a=profiles/${{ matrix.conan_profile }} -s:a build_type=${{ matrix.build_type }} -o:a='&:with_tests=True' --build=missing
      - name: Configure CMake
        run: cmake --preset conan-${{ steps.lower.outputs.build_type_lower }}
        working-directory: ./raktr/
      - name: Build
        run: cmake --build --preset conan-${{ steps.lower.outputs.build_type_lower }} --parallel 10
        working-directory: ./raktr/
      - name: Test
        run: cd build ; ctest -j 10 -C ${{ matrix.build_type }} --output-on-failure
